apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: podinfo-wave-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
